# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Danny White
description:
  Danny White is a digital product designer working on climate mobilisation and
  sustainability.
url: "https://dannywhite.org" # the base hostname & protocol for your site, e.g. http://example.com
author: Danny White

# Build settings
sass:
  style: compressed
compress_html:
  comments: ["<!-- ", " -->"]
  blanklines: true

kramdown:
  # Stop Apple's emoji preference
  footnote_backlink: "&#8617;&#65038;"
  # auto_ids: false: would prevent automatic ids for h2, h3, etc
  auto_ids: true

plugins:
  - jekyll-feed
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /notes/:year/:title
  work:
    output: true
    permalink: /work/:title
    order:
      - time-is-running-out.md
      - environmental-resources-center.md
      - native-checkout.md
      - loupe-2018.md
      - kickstarter-sketch-plugin.md
      - origami.md
      - contextkit.md
      - branded-interactions.md
      - syd.md
      - mumford.md

# Set some defaults to save repetition
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "article"
  - scope:
      path: ""
      type: "work"
    values:
      layout: "work"
      type: "article"
      twitter_card_type: "summary_large_image"

# Exclude directories and/or files from the conversion
exclude:
  - Gemfile
  - Gemfile.lock

# Filtering content
show_drafts: false
# future: false
